from pathlib import Path

from system_testing.cases import ACTION_DISCARD, SYSTEM_TESTING_CASES


class DocGen:
    @staticmethod
    def generate_documentation():
        system_testing_folder = Path(__file__).parent.absolute()
        project_folder = Path(__file__).parent.parent.parent.absolute()
        doc_file = system_testing_folder.parent.parent / "doc" / "system_testing.md"
        doc_content = []

        doc_content.append("WARNING! This is autogenerated file, don't change it manually.")

        for case in SYSTEM_TESTING_CASES:
            index = case["index"]
            relative_image_path = (system_testing_folder / "fixtures" / f"{index}.png").relative_to(project_folder)

            doc_content.append(f"# Case {index}")

            if case["action"] == ACTION_DISCARD:
                doc_content.append(
                    f"`Action: {ACTION_DISCARD}, allowed discard: {', '.join(case['allowed_discards'])}`"
                )

            if case["description"]:
                doc_content.append(case["description"])

            doc_content.append("Reproduce:")
            doc_content.append("> " + case["reproducer_command"])

            doc_content.append(f"![image](../{relative_image_path})")

        doc_file.write_text("\n\n".join(doc_content))
